[package]
name = "modemhandler"
version = "0.1.0"
edition = "2021"
repository = "github.com:Ion-Mobility/modemcli.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modemcli= { path = "modemcli" }
